name: SPI EEPROM Simulation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up docker
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
      
      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          provenance: false
          tags: spieeprom_sim
          load: true

      - name: Run Unit Test
        run: docker run --rm -v ${{github.workspace }}:/project -w /project spieeprom_sim pytest -q

